# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowKursacha.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 600)
        MainWindow.setMinimumSize(QtCore.QSize(650, 600))
        MainWindow.setMaximumSize(QtCore.QSize(650, 600))
        MainWindow.setSizeIncrement(QtCore.QSize(600, 650))
        MainWindow.setBaseSize(QtCore.QSize(600, -31072))
        MainWindow.setStyleSheet("\n"
"background-color: rgb(132, 37, 200);\n"
"font: 75 12pt \"Fixedsys\";\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AccidentsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AccidentsBtn.setGeometry(QtCore.QRect(280, 150, 111, 20))
        self.AccidentsBtn.setStyleSheet("background-color: rgb(255, 207, 64);\n"
"")
        self.AccidentsBtn.setObjectName("AccidentsBtn")
        self.DriversBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DriversBtn.setGeometry(QtCore.QRect(280, 190, 111, 21))
        self.DriversBtn.setStyleSheet("background-color: rgb(255, 207, 64);\n"
"")
        self.DriversBtn.setObjectName("DriversBtn")
        self.FuelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.FuelBtn.setGeometry(QtCore.QRect(280, 210, 111, 21))
        self.FuelBtn.setStyleSheet("background-color: rgb(255, 207, 64);\n"
"")
        self.FuelBtn.setObjectName("FuelBtn")
        self.InspectionsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.InspectionsBtn.setGeometry(QtCore.QRect(280, 170, 111, 21))
        self.InspectionsBtn.setStyleSheet("background-color: rgb(255, 207, 64);\n"
"")
        self.InspectionsBtn.setObjectName("InspectionsBtn")
        self.MaintenanceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.MaintenanceBtn.setGeometry(QtCore.QRect(280, 130, 111, 21))
        self.MaintenanceBtn.setStyleSheet("background-color: rgb(255, 207, 64);\n"
"")
        self.MaintenanceBtn.setObjectName("MaintenanceBtn")
        self.TripsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.TripsBtn.setGeometry(QtCore.QRect(280, 90, 111, 20))
        self.TripsBtn.setStyleSheet("background-color: rgb(255, 207, 64);")
        self.TripsBtn.setObjectName("TripsBtn")
        self.Vehicles = QtWidgets.QPushButton(self.centralwidget)
        self.Vehicles.setGeometry(QtCore.QRect(280, 110, 111, 20))
        self.Vehicles.setStyleSheet("background-color: rgb(255, 207, 64);")
        self.Vehicles.setObjectName("Vehicles")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 610, 26))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vehicles"))
        self.AccidentsBtn.setText(_translate("MainWindow", "Accidents"))
        self.DriversBtn.setText(_translate("MainWindow", "Drivers"))
        self.FuelBtn.setText(_translate("MainWindow", "Fuel"))
        self.InspectionsBtn.setText(_translate("MainWindow", "Inspections"))
        self.MaintenanceBtn.setText(_translate("MainWindow", "Maintenance"))
        self.TripsBtn.setText(_translate("MainWindow", "Trips"))
        self.Vehicles.setText(_translate("MainWindow", "Vehicles"))
